CREATE TABLE IF NOT EXISTS company_assets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    asset_code VARCHAR(20) NOT NULL UNIQUE,
    asset_name VARCHAR(200) NOT NULL,
    description TEXT,
    category VARCHAR(100),
    serial_number VARCHAR(100),
    purchase_date DATE NOT NULL,
    purchase_cost DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(3) DEFAULT 'TZS',
    depreciation_method ENUM('straight_line') DEFAULT 'straight_line',
    useful_life INT NOT NULL DEFAULT 5,
    useful_life_unit ENUM('months','years') DEFAULT 'years',
    residual_value DECIMAL(15,2) DEFAULT 0.00,
    depreciation_start_date DATE NOT NULL,
    depreciation_end_date DATE,
    depreciation_rate DECIMAL(10,4) DEFAULT 0.0000,
    depreciation_per_period DECIMAL(15,2) DEFAULT 0.00,
    accumulated_depreciation DECIMAL(15,2) DEFAULT 0.00,
    current_book_value DECIMAL(15,2) DEFAULT 0.00,
    status ENUM('active','in_storage','under_maintenance','assigned','disposed','sold','written_off','archived') DEFAULT 'active',
    asset_condition ENUM('new','good','fair','poor','damaged') DEFAULT 'new',
    location VARCHAR(200),
    department_id INT,
    assigned_to INT,
    supplier_id INT,
    invoice_number VARCHAR(100),
    warranty_expiry_date DATE,
    notes TEXT,
    created_by INT,
    updated_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    archived_at TIMESTAMP NULL,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
    FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_asset_code (asset_code),
    INDEX idx_status (status),
    INDEX idx_category (category),
    INDEX idx_purchase_date (purchase_date),
    INDEX idx_department (department_id),
    INDEX idx_archived (archived_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
